name: ddgood
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  intl: ^0.18.1
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Pretendard-Bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: Pretendard-Medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.otf
    - family: Pretendard-Regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
    - family: Pretendard-SemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.otf
